### ISSUE TITLE
Does not build with react-native 0.14.2

### ISSUE THREAD

**Issue by moooji** [PrazAs/react-native-charts#2]
When I try to use this plugin with the latest react-native, I get this error:

```
bundle: Created ReactPackager
uncaught error Error: SyntaxError: /Users/steve/Documents/Workspace/react-native/workout/node_modules/react-native-charts/src/components/BarChart/index.js: Unexpected token (12:22)
  10 | 
  11 | export default class BarChart extends React.Component {
> 12 |   static defaultProps = {
     |                       ^
  13 |     showGrid: DEFAULT_SHOW_GRID,
  14 |   }
  15 | 
    at Parser.pp.raise (/Users/steve/Documents/Workspace/react-native/workout/node_modules/react-native/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
```

**Comment by vmandke** [comment]
Are you using babel to transform into JS?

**Comment by danscan** [comment]
@moooji here is the .babelrc from one of the projects I use this in.  It looks like you're getting an error on static props (`es7.classProperties`).  You don't need everything in this .babelrc.

Let me know if that helps.  I'm on vacation until later this week, but will try to respond quickly:)

**Comment by pbattisson** [comment]
@danscan Do you have the link to that .babelrc file? I am getting the same error.

**Comment by danscan** [comment]
@pbattisson try this: https://gist.github.com/danscan/4d64a04368e4a52b91a0

**Comment by pbattisson** [comment]
:clap: Thanks for the help, that file has solved my issues. Will trim it down as needed. Thanks for the help @danscan

**Comment by danscan** [comment]
@pbattisson Great!  Let me know if you have any questions– I've been focused on backend stuff recently, but this project will continue to evolve as we move it to new applications.
