### ISSUE TITLE
Invariant Violation in RN 0.17

### ISSUE THREAD

**Issue by nbastoWM** [PrazAs/react-native-charts#3]
Hi,
I was using the module in RN 0.11 but when I upgraded toa RN 0.17 there's an error: 
![image](https://cloud.githubusercontent.com/assets/15138821/12145277/428719e2-b485-11e5-897a-b9ea2cb160c0.png)

**Comment by danscan** [comment]
@nbastoWM Thank you for reporting the issue.  I'm completely swamped, but will try to get this resolved this weekend.  Should be pretty easy.

**Comment by danscan** [comment]
@nbastoWM Sorry for the delay on this, but I've done a rewrite that touched every file in the project.  The API itself hasn't changed, but I've added `propTypes`, and made a fix to the way the components are exported.  This should fix the issue you encountered.  (current version is `2.0.2`)
